package mealplanner.enums;

public enum SqlSchema {
    MEALS("""
        CREATE TABLE IF NOT EXISTS meals (
            meal_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            category VARCHAR(255),
            meal VARCHAR(255)
        );
    """),
    INGREDIENTS("""
        CREATE TABLE IF NOT EXISTS ingredients (
            ingredient_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ingredient VARCHAR(255),
            meal_id INTEGER,
            FOREIGN KEY (meal_id) REFERENCES meals(meal_id) ON DELETE CASCADE
        );
    """),
    PLAN("""
        CREATE TABLE IF NOT EXISTS plan (
            plan_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            day_of_week VARCHAR(255),
            meal_option VARCHAR(255),
            meal_category VARCHAR(255),
            meal_id INTEGER,
            FOREIGN KEY (meal_id) REFERENCES meals(meal_id) ON DELETE CASCADE
        );
    """);

    private final String sql;

    SqlSchema(String sql) {
        this.sql = sql;
    }

    public String getSql() {
        return sql;
    }
}
